algoritmo "ImparPar"
// Função : Identificar numeros impares
// Autor : Gabriel
// Data : 05/08/2025
// Seção de Declarações 
var

num : inteiro

inicio
Escreva("Digite um número INTEIRO: ")
leia(num)

Escreval("Número: ", num)

se (num % 2 = 0) entao    // O operador % ou mod indica o resto de uma divisão
Escreval("O número: '", num, "' é par.")
senao
Escreval("O número: '", num, "' é ímpar")
fimse
fimalgoritmo
