algoritmo "Hello, World!"
// Função :
// Autor :
// Data : 29/07/2025
// Seção de Declarações 
var

inicio

      Escreval("Olá, mundo!")
      Escreval("Sou um computador!")
      Escreval
      Escreval
      Escreval("Vendo curso de lógica di computations")
      Escreval("Olha, sou uma linguagem em português! ÁÉÍÓÚÃ~E~IÕ~UÇÇ")
      Escreva("Sou eu denovo")
      Escreva("O que será que isso faz?")
      Escreva("Meudeus não tem o \n")

      

fimalgoritmo

