algoritmo "VetorSomaNum"
// Função :
// Autor :
// Data : 13/08/2025
// Seção de Declarações 
var

num : vetor [1..5] de inteiro
soma, i : inteiro

inicio

para i de 1 ate 5 faca

     Escreva("Digite um número: ")
     leia(num [i])

fimpara
 soma <- num[1] + num[2] + num[3] + num[4] + num[5]
 
 Escreval(" ", num[1])
 Escreval(" ", num[2])
 Escreval(" ", num[3])
 Escreval(" ", num[4])
 Escreval("+", num[5])
 Escreval("______")
 Escreval(soma)







fimalgoritmo
