algoritmo "tabuada"
// Função :
// Autor :
// Data : 12/08/2025
// Seção de Declarações 
var

num, fatormult, resul : real
lim : inteiro

inicio

escreva("Digite um número para fazer a tabuada: ")
leia(num)
escreva("Digite o fator para multiplicar a tabuada: ")
leia(fatormult)

lim <- 0

enquanto lim <> fatormult + 1 faca
resul <- lim * num

escreval(num, " x", lim, " =", resul)
lim <- lim + 1

fimenquanto


fimalgoritmo
