algoritmo "tabuada"
// Função :
// Autor :
// Data : 12/08/2025
// Seção de Declarações 
var

num, fatormult, resul : real

inicio

escreva("Digite um número para fazer a tabuada: ")
leia(num)

escreva("Digite o fator para multiplicar a tabuada: ")
leia(fatormult)


enquanto fatormult <> -1 faca

resul <- num * fatorMult

Escreval(num, " x", fatormult, " =", resul)

fatormult <- fatormult - 1
fimenquanto

fimalgoritmo
